version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - mongo
    env_file:
      - ./server/.env.local
    environment:
      ENVIRONMENT: production
      FRONTEND_URL: http://localhost:8000
      ALLOWED_ORIGINS: http://localhost:8000
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB_NAME: codechatter
    ports:
      - "8000:8000"
    volumes:
      - ./server/data:/app/server/data

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
